<h2>Buttons</h2>
<div class="flex">
    <div class="flex__item">
        <h5>Primary</h5>
        <button class="action primary" type="button"><span>Shop All Products</span></button>
    </div>
    <div class="flex__item">
        <h5>Secondary</h5>
        <button class="action secondary" type="button"><span>Learn More</span></button>
    </div>
    <div class="flex__item">
        <h5>Checkout Flow</h5>
        <button class="action flow" type="button"><span>Proceed to Checkout</span></button>
    </div>
    <div class="flex__item">
        <h5>Regular</h5>
        <button class="action" type="button"><span>Submit</span></button>
    </div>
</div>
<div class="flex">    
    <div class="flex__item">
        <h5>Sizes</h5>
        <button class="action large" type="button"><span>Large</span></button>
        <button class="action" type="button"><span>Default</span></button>
        <button class="action small" type="button"><span>Small</span></button>
    </div>
    <div class="flex__item">
        <h5>Disabled</h5>
        <button class="action primary" type="button" disabled=""><span>Inactive</span></button>
    </div>
    <div class="flex__item">
        <h5>Links</h5>
        <a href="#" class="action primary">Link as a button</a>
        <button class="action link" type="button"><span>Button as a link</span></button>
    </div>
</div>
<div class="flex">
    <div class="flex__item">
        <h5>With icon</h5>
        <button class="action tocart" type="button"><i class="rw-icon-cart"></i><span>Add to Cart</span></button>
        <button class="action success" type="button"><i class="rw-icon-tick"></i><span>Accept</span></button>
        <button class="action error" type="button"><i class="rw-icon-close"></i><span>Cancel</span></button>
        <button class="action small error" type="button"><i class="rw-icon-trash"></i><span>Delete</span></button>
    </div>
</div>
<hr class="space">