   <h2>Buttons</h2>
<div class="flex flex-wrap">
    <div class="flex-item">
        <h5>Primary</h5>
        <button class="action primary" type="button"><span>Primary button</span></button>
        <button class="action primary" type="button" disabled=""><span>Disabled Primary button</span></button>
        <a class="action primary">Link as a button</a>
    </div>
    <div class="flex-item">
        <h5>Default</h5>
        <button class="action" type="button"><span>Action</span></button>
        <button class="action" type="button" disabled=""><span>Disbaled Action</span></button>
    </div>
    <div class="flex-item">
        <h5>Sizes</h5>
        <button class="action button--xl" type="button"><span>Extra arge button</span></button>
        <button class="action button--l" type="button"><span>Large button</span></button>
        <button class="action button--m" type="button"><span>Medium button</span></button>
        <button class="action button--s" type="button"><span>Small button</span></button>
    </div>
    <div class="flex-item">
        <h5>Special</h5>
        <button class="action button--link" type="button"><span>Extra arge button</span></button>
        <button class="action button--gradient" type="button"><span>Large button</span></button>
        <button class="action button--icon" type="button"><span>Medium button</span></button>
    </div>
</div>
<hr class="space">