<h2>Color Palette</h2>
<div class="flex flex-wrap">
    <div class="flex-item">
        <h6>accent</h6>
        <div class="color-set">
            <div class="color-box" style="background-color: #8bc53f; color: #fff"">
                <span class="color-variable">@col-accent</span>
                <span class="color-hex">#8bc53f</span>
            </div>
        </div>
    </div>
    <div class="flex-item">
        <h6>alt</h6>
        <div class="color-set">
            <div class="color-box" style="background-color: #f3783b; color: #fff">
                <span class="color-variable">@col-alt</span>
                <span class="color-hex">#f3783b</span>
            </div>
        </div>
    </div>
    <div class="flex-item">
        <h6>black</h6>
        <div class="color-set">
            <div class="color-box" style="background-color: #0a0a0a; color: #fff">
                <span class="color-variable">@col-black</span>
                <span class="color-hex">#0a0a0a</span>
            </div>
        </div>
    </div>
    <div class="flex-item">
        <h6>gray</h6>
        <div class="color-set">
            <div class="color-box" style="background-color: #ccc">
                <span class="color-variable">@col-gray</span>
                <span class="color-hex">#ccc</span>
            </div>
        </div>
    </div>
</div>
<hr class="space">