<h2>Color Palette</h2>
<div class="grid grid-auto">
    <div class="grid-item">
        <h6>primary</h6>
        <div class="color-set">
            <div class="color-box example-box color-primary">@col-primary</div>
        </div>
    </div>
    <div class="grid-item">
        <h6>accent</h6>
        <div class="color-set">
            <div class="color-box example-box color-accent">@col-accent</div>
        </div>
    </div>
    <div class="grid-item">
        <h6>action</h6>
        <div class="color-box example-box color-action">@col-action</div>
        <div class="color-set">
        </div>
    </div>
    <div class="grid-item">
        <h6>success</h6>
        <div class="color-set">
            <div class="color-box example-box color-success">@col-success</div>
        </div>
    </div>
    <div class="grid-item">
        <h6>error</h6>
        <div class="color-set">
            <div class="color-box example-box color-error">@col-error</div>
        </div>
    </div>
    <div class="grid-item">
        <h6>dark</h6>
        <div class="color-set">
            <div class="color-box example-box color-dark">@col-dark</div>
        </div>
    </div>
    <div class="grid-item">
        <h6>neutral</h6>
        <div class="color-set">
            <div class="color-box example-box color-neutral">@col-neutral</div>
        </div>
    </div>
</div>
<hr class="space">