<h2>Color Palette</h2>
<div class="grid grid-auto">
    <div class="grid-item">
        <h6>accent</h6>
        <div class="color-set">
            <div class="color-box example-box" style="background-color: #1979c3; color: #fff">@col-accent<br>#1979c3</div>
        </div>
    </div>
    <div class="grid-item">
        <h6>alt</h6>
        <div class="color-set">
            <div class="color-box example-box" style="background-color: #ce3a1e; color: #fff">@col-alt<br>#ce3a1e</div>
        </div>
    </div>
    <div class="grid-item">
        <h6>black</h6>
        <div class="color-set">
            <div class="color-box example-box" style="background-color: #0a0a0a; color: #fff">@col-black<br>#0a0a0a</div>
        </div>
    </div>
    <div class="grid-item">
        <h6>gray</h6>
        <div class="color-set">
            <div class="color-box example-box" style="background-color: #ccc">@col-gray<br>#ccc</div>
        </div>
    </div>
</div>
<hr class="space">