<h2>Icons</h2>
<div class="flex flex-wrap">
    <div class="flex-item">
        <span class="icon rw-icon-social-pt"></span>
    </div>
    <div class="flex-item">
        <span class="icon rw-icon-social-fb"></span>
    </div>
    <div class="flex-item">
        <span class="icon rw-icon-social-tw"></span>
    </div>
    <div class="flex-item">
        <span class="icon rw-icon-social-ig"></span>
    </div>
    <div class="flex-item">
        <span class="icon rw-icon-cart"></span>
    </div>
    <div class="flex-item">
        <span class="icon rw-icon-zoom"></span>
    </div>
    <div class="flex-item">
        <span class="icon rw-icon-quotes"></span>
    </div>
    <div class="flex-item">
        <span class="icon rw-icon-tooltip"></span>
    </div>
    <div class="flex-item">
        <span class="icon rw-icon-trash"></span>
    </div>
    <div class="flex-item">
        <span class="icon rw-icon-person"></span>
    </div>
    <div class="flex-item">
        <span class="icon rw-icon-close"></span>
    </div>
    <div class="flex-item">
        <span class="icon rw-icon-tick"></span>
    </div>
    <div class="flex-item">
        <span class="icon rw-icon-eyebrow"></span>
    </div>
    <div class="flex-item">
        <span class="icon rw-icon-angle-down"></span>
    </div>
    <div class="flex-item">
        <span class="icon rw-icon-angle-left"></span>
    </div>
    <div class="flex-item">
        <span class="icon rw-icon-angle-right"></span>
    </div>
    <div class="flex-item">
        <span class="icon rw-icon-angle-up"></span>
    </div>
</ul>