<h2>Icons</h2>
<div class="flex flex-wrap">
    <div class="flex-item">
        <div class="icon rw-icon-pinterest"></div>
        <span class="css-mapping">pinterest</span> <span class="char-mapping">6a</span></div>
    <div class="flex-item">
        <div class="icon rw-icon-facebook"></div>
        <span class="css-mapping">facebook</span> <span class="char-mapping">67</span></div>
    <div class="flex-item">
        <div class="icon rw-icon-twitter"></div>
        <span class="css-mapping">twitter</span> <span class="char-mapping">66</span></div>
    <div class="flex-item">
        <div class="icon rw-icon-instagram"></div>
        <span class="css-mapping">instagram</span> <span class="char-mapping">69</span></div>
    <div class="flex-item">
        <div class="icon rw-icon-cart"></div>
        <span class="css-mapping">cart</span> <span class="char-mapping">6c</span></div>
    <div class="flex-item">
        <div class="icon rw-icon-zoom"></div>
        <span class="css-mapping">zoom</span> <span class="char-mapping">6b</span></div>
    <div class="flex-item">
        <div class="icon rw-icon-quotes"></div>
        <span class="css-mapping">quotes</span> <span class="char-mapping">70</span></div>
    <div class="flex-item">
        <div class="icon rw-icon-tooltip"></div>
        <span class="css-mapping">tooltip</span> <span class="char-mapping">6f</span></div>
    <div class="flex-item">
        <div class="icon rw-icon-trash"></div>
        <span class="css-mapping">trash</span> <span class="char-mapping">6e</span></div>
    <div class="flex-item">
        <div class="icon rw-icon-person"></div>
        <span class="css-mapping">person</span> <span class="char-mapping">6d</span></div>
    <div class="flex-item">
        <div class="icon rw-icon-close"></div>
        <span class="css-mapping">close</span> <span class="char-mapping">65</span></div>
    <div class="flex-item">
        <div class="icon rw-icon-angle-down"></div>
        <span class="css-mapping">angle-down</span> <span class="char-mapping">61</span></div>
    <div class="flex-item">
        <div class="icon rw-icon-angle-left"></div>
        <span class="css-mapping">angle-left</span> <span class="char-mapping">62</span></div>
    <div class="flex-item">
        <div class="icon rw-icon-angle-right"></div>
        <span class="css-mapping">angle-right</span> <span class="char-mapping">63</span></div>
    <div class="flex-item">
        <div class="icon rw-icon-angle-up"></div>
        <span class="css-mapping">angle-up</span> <span class="char-mapping">64</span></div>
</ul>