<h2>Layouts</h2>
<h3>Flex</h3>
<div class="flex flex--wrap">
    <div class="flex__item flex__item--25 example-box">.flex__item--25</div>
    <div class="flex__item flex__item--25 example-box">.flex__item--25</div>
    <div class="flex__item flex__item--25 example-box">.flex__item--25</div>
    <div class="flex__item flex__item--25 example-box">.flex__item--25</div>
    <div class="flex__item flex__item--33 example-box">.flex__item--33</div>
    <div class="flex__item flex__item--33 example-box">.flex__item--33</div>
    <div class="flex__item flex__item--33 example-box">.flex__item--33</div>
    <div class="flex__item flex__item--50 example-box">.flex__item--50</div>
    <div class="flex__item flex__item--50 example-box">.flex__item--50</div>
</div>
<h3>Grid</h3>
<div class="grid grid--4">
    <div class="grid__item example-box">.grid__item</div>
    <div class="grid__item example-box">.grid__item</div>
    <div class="grid__item example-box" style="grid-column: 3 / 5">.grid-column(3,5)</div>
    <div class="grid__item example-box" style="grid-column: 1 / 4">.grid-column(1,4)</div>
    <div class="grid__item example-box" style="grid-column: 4 / 5;grid-row: 2 / 5;">.grid-column(4,5)<br>.grid-row(2,5)</div>
    <div class="grid__item example-box" style="grid-column: 1 / 3;grid-row: 3 / 5;">.grid-column(1,3)<br>.grid-row(3,5)</div>
    <div class="grid__item example-box">.grid__item</div>
    <div class="grid__item example-box">.grid__item</div>
    <div class="grid__item example-box" style="grid-column: 1 / 5">.grid-column(1,5)</div>
</div>
<hr class="space">