<h2>Tables</h2>
<div class="table-wrapper orders-recent"><br>
    <table class="data table"><caption class="table-caption">Recent Orders</caption>
        <thead>
        <tr><th class="col id" scope="col">Order #</th><th class="col date" scope="col">Date</th><th class="col shipping" scope="col">Ship To</th><th class="col total" scope="col">Order Total</th><th class="col status" scope="col">Status</th><th class="col actions" scope="col">Action</th></tr>
        </thead>
        <tbody>
        <tr>
            <td class="col id" data-th="Order #">000000002</td>
            <td class="col date" data-th="Date">1/19/17</td>
            <td class="col shipping" data-th="Ship To">Firstname Last</td>
            <td class="col total" data-th="Order Total"><span class="price">$19.52</span></td>
            <td class="col status" data-th="Status">Complete</td>
            <td class="col actions" data-th="Actions"><a class="action view" href="#"><span>View Order</span></a> <a class="action order" href="#"><span>Reorder</span></a></td>
        </tr>
        <tr>
            <td class="col id" data-th="Order #">000000003</td>
            <td class="col date" data-th="Date">1/23/17</td>
            <td class="col shipping" data-th="Ship To">Firstname Last</td>
            <td class="col total" data-th="Order Total"><span class="price">$39.64</span></td>
            <td class="col status" data-th="Status">Pending</td>
            <td class="col actions" data-th="Actions"><a class="action view" href="#"><span>View Order</span></a> <a class="action order" href="#"><span>Reorder</span></a></td>
        </tr>
        <tr>
            <td class="col id" data-th="Order #">000000004</td>
            <td class="col date" data-th="Date">1/28/17</td>
            <td class="col shipping" data-th="Ship To">Firstname Last</td>
            <td class="col total" data-th="Order Total"><span class="price">$259.99</span></td>
            <td class="col status" data-th="Status">Complete</td>
            <td class="col actions" data-th="Actions"><a class="action view" href="#"><span>View Order</span></a> <a class="action order" href="#"><span>Reorder</span></a></td>
        </tr>
        <tr>
            <td class="col id" data-th="Order #">000000005</td>
            <td class="col date" data-th="Date">2/13/17</td>
            <td class="col shipping" data-th="Ship To">Firstname Last</td>
            <td class="col total" data-th="Order Total"><span class="price">$23.19</span></td>
            <td class="col status" data-th="Status">Processing</td>
            <td class="col actions" data-th="Actions"><a class="action view" href="#"><span>View Order</span></a> <a class="action order" href="#"><span>Reorder</span></a></td>
        </tr>
        </tbody>
    </table>
</div>
<hr class="space">