<h2>Tabs</h2>
<div id="tabs" class="product data items tabs" data-mage-init='{"tabs":{"openedState":"active"}}'>
    <div class="data item title" data-role="collapsible">
        <a href="#tab-1" class="data switch" tabindex="-1" data-toggle="switch">Tab 1</a>
    </div>
    <div id="tab-1" class="data item content" data-role="content">
        <h5>Tab 1 content</h5>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitat.</p>
    </div>
    <div class="data item title" data-role="collapsible">
        <a href="#tab-2" class="data switch" tabindex="-1" data-toggle="switch">Tab 2</a>
    </div>
    <div id="tab-2" class="data item content" data-role="content">
        <h5>Tab 2 content</h5>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitat.</p>
    </div>
    <div class="data item title" data-role="collapsible">
        <a href="#tab-3" class="data switch" tabindex="-1" data-toggle="switch">Tab 3</a>
    </div>
    <div id="tab-3" class="data item content" data-role="content">
        <h5>Tab 3 content</h5>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitat.</p>
    </div>
</div>
<hr class="space">