<h2>Tabs</h2>
<div id="tabs" class="product data items tabs" role="tablist">
    <div class="data item title active" data-role="collapsible" role="tab" data-collapsible="true" aria-controls="tab-1" aria-selected="true" aria-expanded="true" tabindex="0"><a class="data switch" tabindex="-1" href="#tab-1" data-toggle="switch">Description</a></div>
    <div id="tab-1" class="data item content" data-role="content" role="tabpanel" aria-hidden="false" style="display: block;">
        <h5>Tab 1 content</h5>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitat.</p>
    </div>
    <div class="data item title" data-role="collapsible" role="tab" data-collapsible="true" aria-controls="tab-2" aria-selected="false" aria-expanded="false" tabindex="0"><a class="data switch" tabindex="-1" href="#tab-2" data-toggle="switch">Care Instructions</a></div>
    <div id="tab-2" class="data item content" data-role="content" role="tabpanel" aria-hidden="true" style="display: none;">
        <h5>Tab 2 content</h5>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitat.</p>
    </div>
    <div class="data item title" data-role="collapsible" role="tab" data-collapsible="true" aria-controls="tab-3" aria-selected="false" aria-expanded="false" tabindex="0"><a class="data switch" tabindex="-1" href="#tab-3" data-toggle="switch">Size Chart</a></div>
    <div id="tab-3" class="data item content" data-role="content" role="tabpanel" aria-hidden="true" style="display: none;">
        <h5>Tab 3 content</h5>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitat.</p>
    </div>
</div>
<hr class="space">