<h2>Typography</h2>
<div class="flex">
    <div class="flex__item flex__item--50">
        <h1>H1 Lorem <em>ipsum</em> dolor</h1>
        <h2>H2 Lorem <em>ipsum</em> dolor</h2>
        <h3>H3 Lorem <em>ipsum</em> dolor</h3>
        <h4>H4 Lorem <em>ipsum</em> dolor</h4>
        <h5>H5 Lorem ipsum dolor</h5>
        <h6>H6 Lorem ipsum dolor</h6>
    </div>

    <div class="flex__item flex__item--50">
        <h2>Paragraphs</h2>
        <p class="lead">Marius aliquet ultricies ante, non faucibus ante gravida sed. Sed ultrices pellentesque purus, vulputate.</p>
        <p>Mauris aliquet <a href="#">link</a> ultricies ante, non <strong>bold</strong> faucibus ante gravida sed. Sed ultrices <em>rendered as italicized text</em> pellentesque purus, vulputate volutpat ipsum hendrerit sed neque..</p>

        <h2>Blockquote</h2>
        <blockquote>Mauris aliquet ultricies ante, non faucibus ante gravida sed. Sed ultrices pellentesque purus, vulputate volutpat ipsum hendrerit sed neque sed sapien rutrum laoreet justo ultrices. In pellentesque lorem condimentum dui morbi pulvinar dui non quam pretium ut lacinia tortor. <small>Someone famous <cite title="Source Title">Source Title</cite></small></blockquote>
    </div>
</div>
<hr class="space">