<h2>Typography</h2>
<div class="table-wrapper">
    <table class="data table typography">
        <tbody>
            <tr>
                <td>Open Sans<br>H1 default</td>
                <td><h1>H1 heading</h1></td>
                <td>@h1__font-size</td>
            </tr>
            <tr>
                <td>Open Sans<br>H2 default</td>
                <td><h2>H2 heading</h2></td>
                <td>@h2__font-size</td>
            </tr>
            <tr>
                <td>Open Sans<br>H3 default</td>
                <td><h3>H3 heading</h3></td>
                <td>@h3__font-size</td>
            </tr>
            <tr>
                <td>Open Sans<br>H4 default</td>
                <td><h4>H4 heading</h4></td>
                <td>@h4__font-size</td>
            </tr>
            <tr>
                <td>Open Sans<br>H5 default</td>
                <td><h5>H5 heading</h5></td>
                <td>@h5__font-size</td>
            </tr>
            <tr>
                <td>Open Sans<br>H6 default</td>
                <td><h6>H6 heading</h6></td>
                <td>@h6__font-size</td>
            </tr>

            <tr>
                <td>Open Sans<br>.heading--first-class</td>
                <td><h1 class="heading--first-class">First class heading</h1></td>
                <td>@font-size__xl</td>
            </tr>
            <tr>
                <td>Open Sans<br>.heading--second-class</td>
                <td><h2 class="heading--second-class">Second class heading</h2></td>
                <td>@font-size__l</td>
            </tr>
            <tr>
                <td>Open Sans<br>.heading--third-class</td>
                <td><h3 class="heading--third-class">Third class heading</h3></td>
                <td>@font-size__s</td>
            </tr>
            <tr>
                <td>Open Sans<br>.heading--fourth-class</td>
                <td><h4 class="heading--fourth-class">Fourth class heading</h4></td>
                <td>@font-size__xs</td>
            </tr>
            <tr>
                <td>Open Sans<br>.heading</td>
                <td><h2 class="heading">Fourth class heading</h2></td>
                <td>@font-weight__semibold</td>
            </tr>
            <tr>
                <td>Open Sans<br>Default paragraph</td>
                <td><p>Paragraph text</p></td>
                <td>@font-size__base</td>
            </tr>
        </tbody>
    </table>
</div>
<hr class="space">